# Generated by Django 4.2.1 on 2023-07-13 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(max_length=200)),
                ('dr_image', models.ImageField(null=True, upload_to='image/')),
                ('dr_department', models.CharField(max_length=200)),
                ('dr_time', models.CharField(max_length=200)),
                ('dr_phone', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200)),
                ('p_address', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('p_phone', models.IntegerField()),
                ('p_age', models.IntegerField()),
                ('p_blood', models.CharField(max_length=300)),
                ('p_image', models.ImageField(null=True, upload_to='image/')),
                ('join_date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField()),
                ('time1', models.TimeField()),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctormodel')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patientmodel')),
            ],
        ),
    ]
