# Generated by Django 4.2.1 on 2023-07-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_appointmentmodel_delete_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
