# Generated by Django 4.2.1 on 2023-07-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_doctormodel_status_patientmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctormodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='patientmodel',
            name='status',
        ),
    ]
