# Generated by Django 4.2.1 on 2023-07-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_appointment_delete_appointmentmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Appointment_patient',
        ),
    ]
