# Generated by Django 4.2.1 on 2023-07-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_appointmentmodel_delete_appointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppointmentModel',
            new_name='PatientAppointment',
        ),
    ]
