# Generated by Django 4.2.1 on 2023-07-19 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_appointmentmodel_patientappointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientAppointment',
            new_name='Appointment',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Doctor',
            new_name='Doctor_name',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='patient_name',
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='app_appointment',
        ),
    ]
