# Generated by Django 4.2.1 on 2023-07-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_dischargemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Doctor_name',
            new_name='Doctor_id',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_name',
            new_name='patient_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
