# Generated by Django 4.2.1 on 2023-07-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_doctor_name_appointment_doctor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dischargemodel',
            name='gst',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dischargemodel',
            name='total_cost',
            field=models.FloatField(),
        ),
    ]
